export const landmarks = [
  {
    name: "Red Fort",
    description: "A historic fort in Delhi.",
    image: "/landmarks/redfort.jpg",
    funFact: "It was the main residence of the Mughal emperors.",
  },
  {
    name: "India Gate",
    description: "A war memorial in Delhi.",
    image: "/landmarks/IndiaGate.jpg",
    funFact: "Commemorates 84,000 soldiers.",
  },
  {
    name: "Qutub Minar",
    description: "Tallest brick minaret.",
    image: "/landmarks/QutubMinar.jpg",
    funFact: "Built in 1199 by Qutb-ud-din Aibak.",
  },
  {
    name: "Taj Mahal",
    description: "White marble mausoleum in Agra.",
    image: "/landmarks/tajmahal.jpg",
    funFact: "Built by Shah Jahan for Mumtaz.",
    location: { lat: 27.1751, lng: 78.0421 },
  },
  {
    name: "Gateway of India",
    description: "Iconic arch in Mumbai.",
    image: "/landmarks/gatewayofindia.jpg",
    funFact: "Built to commemorate King George V's visit.",
    location: { lat: 18.9218, lng: 72.8347 },
  },
  {
    name: "Charminar",
    description: "A 16th-century mosque in Hyderabad.",
    image: "/landmarks/Charminar.jpg",
    funFact: "Has four grand arches facing each direction.",
    location: { lat: 17.3616, lng: 78.4747 },
  },
  {
    name: "Mysore Palace",
    description: "Royal residence in Karnataka.",
    image: "/landmarks/MysorePalace.jpg",
    funFact: "Lit with 100,000 bulbs every Sunday.",
    location: { lat: 12.3051, lng: 76.6551 },
  },
  {
    name: "Meenakshi Temple",
    description: "Dravidian-style temple in Madurai.",
    image: "/landmarks/MeenakshiTemple.jpg",
    funFact: "Has 14 gopurams and 33,000 sculptures.",
    location: { lat: 9.9195, lng: 78.1194 },
  },
  {
    name: "Jagannath Temple",
    description: "Famous Hindu temple in Puri.",
    image: "/landmarks/JagannathTemple.jpg",
    funFact: "Hosts the grand Rath Yatra every year.",
    location: { lat: 19.8041, lng: 85.8166 },
  },
  {
    name: "Howrah Bridge",
    description: "Suspension bridge in Kolkata.",
    image: "/landmarks/HowrahBridge.jpg",
    funFact: "One of the busiest cantilever bridges in the world.",
    location: { lat: 22.5850, lng: 88.3468 },
  },
];
